# Generated by Django 4.2.7 on 2023-11-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etender', '0002_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_name', models.CharField(max_length=100, verbose_name='Наименование закупки')),
                ('purchase_method', models.CharField(max_length=100, verbose_name='Метод закупки')),
                ('purchase_number', models.CharField(max_length=100, verbose_name='Номер закупки')),
                ('purchase_type', models.CharField(max_length=100, verbose_name='Вид закупок')),
                ('organization_name', models.CharField(max_length=100, verbose_name='Наименование организации')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Планируемая сумма')),
                ('publication_date', models.DateTimeField(verbose_name='Дата опубликования')),
                ('proposal_deadline', models.DateTimeField(verbose_name='Срок подачи предложений поставщиков')),
            ],
        ),
    ]
